export interface ListaPaisesI{
    name:string;
    topLevelDomain:string;
    alpha2Code:string;
    alpha3Code:string;
    callingCodes:string;
    capital:string;
    altSpellings:string;
    region:string;
    subregion:string;
    population:string;
    latlng:string;
    demonym:string;
    area:string;
    gini:string;
    timezones:string;
    borders:string;
    nativeName:string;
    numericCode:string;
    currencies:string;
    languages:string;
    translationsv
    flag:string;
    regionalBlocsv:string;
    cioc:string;
}